[project]
name = "solid-carnival"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ansible-core>=2.18.5",
]

[dependency-groups]
dev = [
    "ansible-lint>=25.2.1",
    "pre-commit>=4.2.0",
]
